### PR TITLE
Create pie_function

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by yongsuH — APPROVED** [review]
Good work!

**Comment by steveiaco** [comment]
Shouldn't we be calculating this in real time? Instead of storing it as a constant?

**Comment by ghost** [comment]
yes I will be changing that

**Comment by steveiaco** [comment]
Is this still necessary to merge? We have the constants file now with the same functionality

**Comment by steveiaco** [comment]
Not needed due to the new Constants.py file

**Pull request closed without merging**
