### PR TITLE
added degree/radians conversion for cosh and sine. Updated constants …

### PR DESCRIPTION
**Pull request by whuras**
…file with import alias' due to errors.

### CODE REVIEW

**Comment by steveiaco** [comment]
Do you think you can add instructions to the cosh / sin function on how to use this and what it defaults to?

**Comment by steveiaco** [comment]
There seems to be an issue with sin, inputting sin:5,0 or sin:5,1 yields the same answer for me

**Comment by whuras** [comment]
> Do you think you can add instructions to the cosh / sin function on how to use this and what it defaults to?

Done.



> There seems to be an issue with sin, inputting sin:5,0 or sin:5,1 yields the same answer for me

Fixed.

**Review by steveiaco — APPROVED** [review]

**Review by seanheinrichs — APPROVED** [review]
LGTM!

**Pull request merged**
