### PR TITLE
Updated formatted to align with PEP8 guidelines.

### PR DESCRIPTION
**Pull request by whuras**
To the best of my ability..

### CODE REVIEW

**Comment by steveiaco** [comment]
Looks good to me, looks like there are conflicts though

**Comment by steveiaco** [comment]
Actually wait, I think you accidentally included some binary files, can you delete them?

**Comment by whuras** [comment]
> Actually wait, I think you accidentally included some binary files, can you delete them?

done

**Review by steveiaco — APPROVED** [review]
nice

**Pull request merged**
