### PR TITLE
updated syntax error in x assignment.

### PR DESCRIPTION
**Pull request by whuras**

### CODE REVIEW

**Review by seanheinrichs — APPROVED** [review]

**Comment by seanheinrichs** [comment]
working for me, just need to fix the merge conflict. The file was renamed to cosh.py (lowercase) in steve's PR

**Review by steveiaco — APPROVED** [review]
looks good to me

**Comment by steveiaco** [comment]
Seems like the merge conflict has to do with the file names cases. Master has all lower-case and this branch still has upper and lowercase. I'm going to rebase your branch on master to try to fix this without breaking my head over the fact that windows ignores file name case

**Comment by steveiaco** [comment]
Accidentally closed the PR, whoops!

**Comment by steveiaco** [comment]
I had to force push, so your local branch may be messed up if you don't reset your head to the remote branch.

 Ready to merge!

**Pull request merged**
