### PR TITLE
Power Function

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by steveiaco** [comment]
This needs to be implemented using exponentiation by squaring

**Review by steveiaco — APPROVED** [review]
Looks good to me! Thanks Amina!

**Comment by ghost** [comment]
look good, but shouldn't we specify how many number after the decimal point ?

**Comment by steveiaco** [comment]
i don't think it's necessary, we can truncate/round numbers once we return to main and we display them to the user

**Comment by ghost** [comment]
Perfect then!

**Pull request merged**
